# In this file we will evaluate the DVHs for the first three patients

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
fraction_dictionary = {
    '1a': 0,
    '1aA': 1,
    '1aB': 2,
    '1aC': 3,
    '1aD': 4,
    '1aE': 5,
}

## Code definition


In [26]:
overlaps_3 = np.array([9.08,19.79,6.02,9.45,19.59,12.62])
overlaps_14 = np.array([2.88,3.35,3.35,0.53,1.92,3.66])
overlaps_18 = np.array([0.92, 0.83, 1.08, 1.91, 0.00, 0.58])
overlaps_25 = np.array([0.41,0.44,0.75,0.00,0.00,0.38])
overlaps_26 = np.array([2.11,2.14,0.87,3.57,2.59,1.91])
overlaps_49 = np.array([4.27,5.91,3.28,3.87,4.18,8.36])

overlaps = [overlaps_3, overlaps_14, overlaps_18, overlaps_25, overlaps_26, overlaps_49]

prescribed_dose_3 = 33
prescribed_dose_14 = 35
prescribed_dose_18 = 35
prescribed_dose_25 = 35
prescribed_dose_26 = 35
prescribed_dose_49 = 40

prescribed_doses = [prescribed_dose_3, prescribed_dose_14, prescribed_dose_18, prescribed_dose_25, prescribed_dose_26, prescribed_dose_49]


## use steepness

In [22]:
import adaptive_fractionation_overlap as af
intercept = -0.660504
slope = -0.65

doses, accum, total_penalty = af.adaptfx_full(volumes = overlaps_3, number_of_fractions= 5, min_dose = 6, max_dose = 10, mean_dose = prescribed_dose_3/5, dose_steps = 0.5)

0 6.0
benefit 2.434320719999997
penalty 0.0
1 8.0
benefit 0
penalty 16.522033920000002
2 7.0
benefit 0
penalty 9.99424032
3 6.0
benefit 2.4109207199999974
penalty 0.0
4 6.0
benefit 1.595430719999998
penalty 0.0


In [23]:
def penalty_calc_full(overlaps, dose, min_dose, mean_dose = None):
    if mean_dose is None:
        mean_dose = dose
    penalties = []
    for overlap in overlaps:
        steepness = np.abs(intercept + slope * overlap)
        penalty = -af.penalty_calc_single(dose, min_dose, mean_dose, overlap, steepness)
        penalties.append(penalty)
    print(np.sum(penalties))
    return np.array(penalties)

In [24]:
standard_penalties = penalty_calc_full(overlaps_3[1:], 6.6, 6)
total_penalty - standard_penalties.sum()

-40.48199999999997


20.40639791999996

In [30]:
benefits = []
doses_all = []
total_penalties = []
for index in range(len(overlaps)):
    doses, accum, total_penalty = af.adaptfx_full(volumes = overlaps[index], number_of_fractions= 5, min_dose = 6, max_dose = 10, mean_dose = prescribed_doses[index]/5, dose_steps = 0.5)
    standard_penalties = penalty_calc_full(overlaps[index][1:], prescribed_doses[index]/5, 6)
    benefits.append(total_penalty - standard_penalties.sum())
    doses_all.append(doses)
    total_penalties.append(total_penalty)


0 6.0
benefit 2.434320719999997
penalty 0.0
1 8.0
benefit 0
penalty 16.522033920000002
2 7.0
benefit 0
penalty 9.99424032
3 6.0
benefit 2.4109207199999974
penalty 0.0
4 6.0
benefit 1.595430719999998
penalty 0.0
-40.48199999999997
0 6.0
benefit 1.419002
penalty 0.0
1 6.0
benefit 1.419002
penalty 0.0
2 9.5
benefit 0
penalty 4.9956375
3 7.5
benefit 0
penalty 3.118563
4 6.0
benefit 1.519752
penalty 0.0
-12.81
0 7.5
benefit 0
penalty 1.3950004999999999
1 6.0
benefit 0.681252
penalty 0.0
2 6.0
benefit 0.951002
penalty 0.0
3 8.5
benefit 0
penalty 0.7430669999999999
4 7.0
benefit 0
penalty 0.58
-4.4
0 6.0
benefit 0.473252
penalty 0.0
1 6.0
benefit 0.574002
penalty 0.0
2 8.0
benefit 0
penalty 0.330252
3 8.0
benefit 0
penalty 0.330252
4 7.0
benefit 0
penalty 0.38
-1.5699999999999998
0 6.0
benefit 1.0257520000000002
penalty 0.0
1 8.0
benefit 0
penalty 2.353002
2 6.0
benefit 1.490502
penalty 0.0
3 7.5
benefit 0
penalty 4.1780005
4 7.5
benefit 0
penalty 3.1027505
-11.08
0 6.0
benefit 9.004008
penal

In [32]:
doses_all

[array([6., 8., 7., 6., 6.]),
 array([6. , 6. , 9.5, 7.5, 6. ]),
 array([7.5, 6. , 6. , 8.5, 7. ]),
 array([6., 6., 8., 8., 7.]),
 array([6. , 8. , 6. , 7.5, 7.5]),
 array([6. , 9.5, 9.5, 9. , 6. ])]

In [28]:
benefits

[20.40639791999996,
 9.053555500000002,
 3.314186500000001,
 1.57675,
 3.9625010000000005,
 26.4246925]